language: node_js
node_js:
  - '8'
before_deploy:
  ./build-binary.sh linux
deploy:
  provider: releases
  api_key:
    secure: adeL+UGFBd5kDqN+7zN8j55ngskdM+KtSt58UWNajscKpc8D9Sqj7cPKECpIbhbAqaERZV6fcfrRlFSHW5BGfeZjPuU++SlWrmVewycaehnVbBnXoMHtBfTL9KUc5uOHlMSxwyd+FtS5N00DrNsR2coPA8b3Zi4DOYM8PVpQ6LU=
  file: linux.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: enketo/enketo-validate
    branch: feature/build-script
