language: node_js
node_js:
  - '8'
os:
  - linux
  - osx
before_deploy:
  - sudo apt-get -qq update
  - sudo apt-get install -y zip
  - sh ./build-binary.sh
deploy:
  provider: releases
  api_key:
    secure: adeL+UGFBd5kDqN+7zN8j55ngskdM+KtSt58UWNajscKpc8D9Sqj7cPKECpIbhbAqaERZV6fcfrRlFSHW5BGfeZjPuU++SlWrmVewycaehnVbBnXoMHtBfTL9KUc5uOHlMSxwyd+FtS5N00DrNsR2coPA8b3Zi4DOYM8PVpQ6LU=
  file_glob: true
  file: 
    ./*.zip
  skip_cleanup: true
  on:
    repo: enketo/enketo-validate
    branch: feature/build-script
